In [4]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv("Clean_Ecommerce.csv")

In [6]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,...,0,UPI,Pending,07-03-2025,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,...,0,Card,Pending,02-09-2025,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,...,0,COD,Returned,05-08-2025,5997.0,5997.0,1199.4,May,2025.0,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193,Mumbai,Maharashtra,Mouse,Electronics,3,...,0,Wallet,Cancelled,10-02-2025,1497.0,1497.0,299.4,February,2025.0,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,Up,Mouse,Electronics,4,...,0,Card,Returned,17-02-2025,39996.0,39996.0,7999.2,February,2025.0,Monday

In [7]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:12345@localhost/ecommerce')

In [8]:
df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

380

In [9]:
df.shape

(380, 21)

In [10]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,...,0,UPI,Pending,07-03-2025,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,...,0,Card,Pending,02-09-2025,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,...,0,COD,Returned,05-08-2025,5997.0,5997.0,1199.4,May,2025.0,Tuesday
3,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193,Mumbai,Maharashtra,Mouse,Electronics,3,...,0,Wallet,Cancelled,10-02-2025,1497.0,1497.0,299.4,February,2025.0,Monday
4,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,Up,Mouse,Electronics,4,...,0,Card,Returned,17-02-2025,39996.0,39996.0,7999.2,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,Up,Mouse,Electronics,4,...,0,Card,Returned,17-02-2025,39996.0,39996.0,7999.2,February,2025.0,Monday
376,ORD1609,NaN,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,...,0,Wallet,Pending,NaN,2998.0,2998.0,599.6,NaN,NaN,NaN
377,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,...,0,NetBanking,Delivered,10-04-2025,NaN,NaN,NaN,April,2025.0,Thursday
378,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,...,0,COD,Pending,11-01-2025,2997.0,2997.0,599.4,January,2025.0,Saturday
379,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,...,0,COD,Cancelled,03-09-2025,2997.0,2997.0,599.4,March,2025.0,Monday